export const GET_TRANSAKSI = "GET_TRANSAKSI"
export const GET_TRANSAKSI_SUCCESS = "GET_TRANSAKSI_SUCCESS"
export const GET_TRANSAKSI_FAILED = "GET_TRANSAKSI_FAILED"

export const ADD_TRANSAKSI = "ADD_TRANSAKSI"
export const ADD_TRANSAKSI_SUCCESS = "ADD_TRANSAKSI_SUCCESS"
export const ADD_TRANSAKSI_FAILED = "ADD_TRANSAKSI_FAILED"